params:
  PATH: data/
  MODEL_PATH: model/
  MAX_LEN: 128
  BATCH_SIZE: 2
  HUG_FACE: cointegrated/rubert-tiny2
  SEED: 42


model:
  num_classes: 2
  dropout_rate: 0.1

trainer:
  lr: 3e-4
  n_epochs: 2
  weight_decay: 1e-6

test_params:
    batch_size: ${params.BATCH_SIZE}
    shuffle: False
    num_workers: 0

train_params:
    batch_size: ${params.BATCH_SIZE}
    shuffle: True
    num_workers: 0
